# File: alphas/__init__.py

from .base_alpha import BaseAlpha
from .alpha1_donchian import Alpha1Donchian
from .alpha2_zscore_basis import Alpha2ZScoreBasis
from .alpha3_bvm import Alpha3BVM
from .alpha4_dbac_kinetic import Alpha4DBACKinetic
from .alpha5_oftp import Alpha5OFTP
from .alpha6_vsbv import Alpha6VSBV
from .alpha7_ppe import Alpha7PPE
from .alpha8_ppex_vmi import Alpha8PPEX
from .alpha9_erm import Alpha9ERM
from .alpha10_kei import Alpha10KEI
from .alpha11_gravity import Alpha11Gravity
from .alpha14_vwba import Alpha14VWBA
from .alpha15_bivs_pro import Alpha15BIVSPro
from .alpha16_fer import Alpha16FER
from .alpha17_bkg import Alpha17BKG
from .alpha18_idg import Alpha18IDG
from .alpha19_bta import Alpha19BTA
from .alpha20_epe import Alpha20EPE
from .alpha21_vada import Alpha21VADA
from .alpha22_qvw import Alpha22QVW
from .alpha23_tcom import Alpha23TCOM
from .alpha24_sfpe import Alpha24SFPE
from .alpha25_sofu import Alpha25SOFU
from .alpha26_mir import Alpha26MIR
from .alpha27_tpe import Alpha27TPE
from .alpha28_psev import Alpha28PSEV
from .alpha29_ova import Alpha29OVA
from .alpha30_iaa import Alpha30IAA
from .alpha31_erd import Alpha31ERD
from .alpha32_bavc_v2 import Alpha32BAVCV2
from .alpha33_vwpd import Alpha33VWPD
from .alpha34_lva import Alpha34LVA
from .alpha35_pdiofa import Alpha35PDIOFA
from .alpha36_cvr import Alpha36CVR
from .alpha37_wrm import Alpha37WRM
from .alpha38_vwpd import Alpha38VWPD
from .alpha39_lvm import Alpha39LVM
from .alpha40_mmc import Alpha40MMC
from .alpha41_cff import Alpha41CFF
from .alpha42_vva import Alpha42VVA
from .alpha43_kim import Alpha43KIM
from .alpha44_liquidity_impulse import Alpha44LiquidityImpulse
from .alpha46_mcm import Alpha46MCM
from .alpha48_tpt import Alpha48TPT
from .alpha49_lsm import Alpha49LSM
from .alpha50_cofc import Alpha50COFC
from .alpha51_er import Alpha51ER
from .alpha53_ked import Alpha53KED
from .alpha54_lai import Alpha54LAI
from .alpha55_vcd import Alpha55VCD
from .alpha56_vsar import Alpha56VSAR
from .alpha57_lvr import Alpha57LVR
from .alpha58_ofv import Alpha58OFV
from .alpha59_lid import Alpha59LID
from .alpha60_lvvi import Alpha60LVVI
from .alpha61_flux import Alpha61FLUX
from .alpha62_ofild import Alpha62OFILD
from .alpha63_bec import Alpha63BEC
from .alpha64_lir import Alpha64LIR
from .alpha65_pet import Alpha65PET
from .alpha66_gbd import Alpha66GBD
from .alpha67_ve import Alpha67VE
from .alpha68_cvp import Alpha68CVP
from .alpha69_vwpr import Alpha69VWPR
from .alpha70_gae import Alpha70GAE
from .alpha71_vmb import Alpha71VMB
from .alpha72_cmcd import Alpha72CMCD
from .alpha73_lfi import Alpha73LFI
from .alpha74_lvdr import Alpha74LVDR
from .alpha75_tcd import Alpha75TCD
from .alpha76_lva import Alpha76LVA
from .alpha77_vwit import Alpha77VWIT
from .alpha78_lvi import Alpha78LVI
from .alpha79_tc import Alpha79TC
